# if given will override the device setting in gym. 
env:
  numEnvs: 2 # 10 4096
  envSpacing: 1 # [m]

  plane:
    staticFriction: 1  # [-]
    dynamicFriction: 1 # [-]
    restitution: 0.00  # [-]

  bezInitState:
    pos: [ 0.0, 0.0, 0.37 ] # xyz [m] 0.37 for default or 0.29 for ready
    rot: [ 0.0, 0.0, 0.0, 1.0 ] # xyzw [quat] 0, -0.707, 0, -0.707 for flat 0.0, 0.0, 0.0, 1.0 for standing up
    vLinear: [ 0.0, 0.0, 0.0 ]  # xyz [m/s]
    vAngular: [ 0.0, 0.0, 0.0 ]  # xyz [rad/s]

  ballInitState:
    pos: [ 0.15, 0, 0.1 ] # xyz [m]
    rot: [ 0.0, 0.0, 0.0, 1.0 ] # xyzw [quat]
    vLinear: [ 0.0, 0.0, 0.0 ]  # xyz [m/s]
    vAngular: [ 0.0, 0.0, 0.0 ]  # xyz [rad/s]

  control:
    # PD Drive parameters:
    stiffness: 100 # [N*m/rad]
    damping: 0.0    # [N*m*s/rad]
    actionScale: 0.5 # ?
    controlFrequencyInv: 1 # 60 Hz

  defaultJointAngles: # = target angles when action = 0.0
    right_leg_motor_0: 0.0 # [rad]
    right_leg_motor_1 : 0.0 # [rad]
    right_leg_motor_2: 0 # [rad]
    right_leg_motor_3: 0.0 # [rad]
    right_leg_motor_4: 0 # [rad]
    right_leg_motor_5: 0.0 # [rad]
    left_leg_motor_0: 0.0 # [rad]
    left_leg_motor_1: 0.0 # [rad]
    left_leg_motor_2: 0 # [rad]
    left_leg_motor_3: 0 # [rad]
    left_leg_motor_4: 0 # [rad]
    left_leg_motor_5: 0.0 # [rad]
    right_arm_motor_0: 0.0 # [rad]
    right_arm_motor_1: 0.0 # [rad]
    left_arm_motor_0: 0.0 # [rad]
    left_arm_motor_1: 0.0 # [rad]
    head_motor_0: 0.0 # [rad]
    head_motor_1: 0.0 # [rad]

  readyJointAngles: # = target angles when action = 0.0
    right_leg_motor_0: 0.0 # [rad]
    right_leg_motor_1: 0.0 # [rad]
    right_leg_motor_2: 0.564 # [rad]
    right_leg_motor_3: -1.176 # [rad]
    right_leg_motor_4: 0.613 # [rad]
    right_leg_motor_5: 0.0 # [rad]
    left_leg_motor_0: 0.0 # [rad]
    left_leg_motor_1: 0.0 # [rad]
    left_leg_motor_2: 0.564 # [rad]
    left_leg_motor_3: -1.176 # [rad]
    left_leg_motor_4: 0.613 # [rad]
    left_leg_motor_5: 0.0 # [rad]
    right_arm_motor_0: 0.0 # [rad]
    right_arm_motor_1: 1.5 # [rad]
    left_arm_motor_0: 0.0 # [rad]
    left_arm_motor_1: 1.5 # [rad]
    head_motor_0: 0.0 # [rad]
    head_motor_1: 0.0 # [rad]

  urdfAsset:
    collapseFixedJoints: False
    fixBaseLink: False
    replace_cylinder_with_capsule: False
    flip_visual_attachments: False
    density: 0.001
    angular_damping: 0.0
    linear_damping: 0.0
    thickness: 0.01
    disable_gravity: False
    armature: 0.01
    defaultDofDriveMode: 1 # see GymDofDriveModeFlags (0 is none, 1 is pos tgt, 2 is vel tgt, 4 effort)


  learn:
    # rewards
    linearVelocityXYRewardScale: 1.0
    angularVelocityZRewardScale: 0.5
    torqueRewardScale: -0.000025

    # normalization
    linearVelocityScale: 2.0
    angularVelocityScale: 0.25
    dofPositionScale: 1.0
    dofVelocityScale: 0.05

    # episode length in seconds
    episodeLength_s: 50

  # viewer cam:
  viewer:
    refEnv: 0
    pos: [ 1, 1, 1 ]  # [m]
    lookat: [ 0, 0, 0 ]  # [m]

  asset:
    assetRoot: resources/assets
    assetFileNameBez: bez/model/soccerbot_box.urdf
    assetFileNameBall: objects/ball.urdf


sim:
  substeps: 2
  gravity: [0., 0. ,-9.81]  # [m/s^2]
  up_axis: 1  # 0 is y, 1 is z

  physx:
    num_threads: 4
    solver_type: 1  # 0: pgs, 1: tgs
    num_position_iterations: 4
    num_velocity_iterations: 1
    contact_offset: 0.002
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1000.0
    use_gpu_pipeline: True

task:
  randomize: False
